[versions]
kotlin = "1.9.22"
agp = "7.4.1"
detekt = "1.23.5"
ktlint = "12.1.0"
versions = "0.51.0"
firebaseAppdistribution = "4.2.0"
grgit = "5.0.0"
publish = "0.14.0"
okhttp = "4.11.0"
moshi = "1.15.0"
retrofit = "2.9.0"
junit = "4.13.2"
ksp = "1.9.22-1.0.17"

[libraries]
agp = { module = "com.android.tools.build:gradle", version.ref = "agp" }
okhttp = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp" }
moshi = { module = "com.squareup.moshi:moshi", version.ref = "moshi" }
moshiCodgen = { module = "com.squareup.moshi:moshi-kotlin-codegen", version.ref = "moshi" }
okhttpLogging = { module = "com.squareup.okhttp3:logging-interceptor", version.ref = "okhttp" }
firebaseAppdistribution = { module = "com.google.firebase:firebase-appdistribution-gradle", version.ref = "firebaseAppdistribution" }
retrofit = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit" }
retrofitMoshi = { module = "com.squareup.retrofit2:converter-moshi", version.ref = "retrofit" }
grgitCore = { module = "org.ajoberstar.grgit:grgit-core", version.ref = "grgit" }
grgitGradle = { module = "org.ajoberstar.grgit:grgit-gradle", version.ref = "grgit" }
junit = { module = "junit:junit", version.ref = "junit" }

kotlin-plugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
detekt-plugin = { module = "io.gitlab.arturbosch.detekt:detekt-gradle-plugin", version.ref = "detekt" }
ksp-plugin = { module = "com.google.devtools.ksp:com.google.devtools.ksp.gradle.plugin", version.ref = "ksp" }

[plugins]
detekt = { id = "io.gitlab.arturbosch.detekt", version.ref = "detekt" }
ktlint = { id = "org.jlleitschuh.gradle.ktlint", version.ref = "ktlint" }
versionsManes = { id = "com.github.ben-manes.versions", version.ref = "versions" }
agp = { id = "com.android.application", version.ref = "agp" }
firebaseAppdistribution = { id = "com.google.firebase.appdistribution", version.ref = "firebaseAppdistribution" }
grgit = { id = "org.ajoberstar.grgit", version.ref = "grgit" }
publish = { id = "com.gradle.plugin-publish", version.ref = "publish" }
kotlin = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
